# Generated by Django 4.2.11 on 2024-09-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'verbose_name': 'Campaña', 'verbose_name_plural': 'Campañas'},
        ),
        migrations.AlterModelOptions(
            name='compensationfund',
            options={'verbose_name': 'Caja de Compensación', 'verbose_name_plural': 'Cajas de Compensación'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='headquarters',
            options={'verbose_name': 'Sede', 'verbose_name_plural': 'Sedes'},
        ),
        migrations.AlterModelOptions(
            name='healthprovider',
            options={'verbose_name': 'Proveedor de Salud', 'verbose_name_plural': 'Proveedores de Salud'},
        ),
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'verbose_name': 'Gerencia', 'verbose_name_plural': 'Gerencias'},
        ),
        migrations.AlterModelOptions(
            name='pensionfund',
            options={'verbose_name': 'Fondo de Pensiones', 'verbose_name_plural': 'Fondos de Pensiones'},
        ),
        migrations.AlterModelOptions(
            name='savingfunds',
            options={'verbose_name': 'Cesantía', 'verbose_name_plural': 'Cesantías'},
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='code',
        ),
        migrations.RemoveField(
            model_name='compensationfund',
            name='code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
        migrations.RemoveField(
            model_name='headquarters',
            name='code',
        ),
        migrations.RemoveField(
            model_name='healthprovider',
            name='code',
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='code',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='code',
        ),
        migrations.RemoveField(
            model_name='management',
            name='code',
        ),
        migrations.RemoveField(
            model_name='pensionfund',
            name='code',
        ),
        migrations.RemoveField(
            model_name='savingfunds',
            name='code',
        ),
    ]
