# Generated by Django 4.2.11 on 2024-09-05 19:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0002_alter_campaign_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Identification must be exactly 10 digits.', regex='^[0-9]{10}$')])),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=2)),
                ('birth_date', models.DateField()),
                ('expedition_place', models.CharField(max_length=100)),
                ('expedition_date', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('rh', models.CharField(max_length=2)),
                ('civil_status', models.CharField(choices=[('S', 'Soltero(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('U', 'Unión Libre'), ('P', 'Separado(a)'), ('V', 'Viudo(a)')], max_length=1)),
                ('sons', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('corporate_email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compensation_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.compensationfund')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.department')),
                ('health_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.healthprovider')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.jobtitle')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.locality')),
                ('pension_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.pensionfund')),
                ('saving_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.savingfunds')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'indexes': [models.Index(fields=['identification'], name='employees_e_identif_e4c381_idx'), models.Index(fields=['email'], name='employees_e_email_8f5bbc_idx')],
            },
        ),
    ]
