# Generated by Django 5.0.7 on 2024-09-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_cell_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='stratum',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=1, verbose_name='Estrato'),
        ),
    ]
