# Generated by Django 5.0.7 on 2024-09-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_stratum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='civil_status',
            field=models.CharField(choices=[('Soltero(a)', 'Soltero(a)'), ('Unión Libre', 'Unión Libre'), ('Casado(a)', 'Casado(a)'), ('Divorciado(a)', 'Divorciado(a)'), ('Separado(a)', 'Separado(a)'), ('Viudo(a)', 'Viudo(a)')], max_length=25, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Otro', 'Otro'), ('Abuelo(a)', 'Abuelo(a)'), ('Amigo(a)', 'Amigo(a)'), ('Hermano(a)', 'Hermano(a)'), ('Esposo(a)', 'Esposo(a)'), ('Hijo(a)', 'Hijo(a)'), ('Tío(a)', 'Tío(a)'), ('Primo(a)', 'Primo(a)'), ('Familiar', 'Familiar')], max_length=100),
        ),
    ]
