# Generated by Django 5.0.7 on 2024-09-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_photo_alter_employee_business_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='windows_user',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Usuario de Windows'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='corporate_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Electrónico Corporativo'),
        ),
    ]
