# Generated by Django 5.0.7 on 2024-09-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employee_corporate_email_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='identification',
            field=models.IntegerField(max_length=15, unique=True, verbose_name='Identificación'),
        ),
    ]
