# Generated by Django 5.0.7 on 2024-09-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_employee_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='appointment_date',
            field=models.DateField(null=True, verbose_name='Fecha de Nombramiento'),
        ),
    ]
