# Generated by Django 5.1 on 2024-09-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_employee_cell_phone_alter_employee_fixed_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='remote_work_application_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Aplicación de Teletrabajo'),
        ),
    ]
