# Generated by Django 5.1 on 2024-09-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='legacy_appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nombramiento (LEGADO)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='legacy_health_provider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CAMBIOS EPS (LEGADO)'),
        ),
    ]
