# Generated by Django 5.1 on 2024-09-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_remove_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='legacy_appointment_date',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Fecha de Nombramiento (LEGADO)'),
        ),
    ]
