# Generated by Django 5.1 on 2024-09-13 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_alter_employee_legacy_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=4, null=True, verbose_name='Talla de Camisa'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shoe_size',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(25), django.core.validators.MaxValueValidator(50)], verbose_name='Talla de Zapato'),
        ),
    ]
