# Generated by Django 5.1 on 2024-09-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_employee_rehire_eligibility_employee_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
