# Generated by Django 5.1 on 2024-10-25 19:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import employees.models
import employees.utilities


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0009_jobtitle_rank"),
        ("employees", "0035_alter_employee_memo_1_alter_employee_memo_2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    employees.models.models.CharField(
                        max_length=255, verbose_name="Dirección"
                    ),
                ),
                (
                    "neighborhood",
                    employees.models.models.CharField(
                        max_length=100, verbose_name="Barrio"
                    ),
                ),
                (
                    "fixed_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(7)],
                        verbose_name="Teléfono Fijo",
                    ),
                ),
                (
                    "cell_phone",
                    employees.models.models.CharField(
                        max_length=15,
                        validators=[django.core.validators.MinLengthValidator(10)],
                        verbose_name="Celular",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "corporate_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="Correo Electrónico Corporativo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Información de Contacto",
                "verbose_name_plural": "Informaciones de Contacto",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "education_level",
                    employees.models.models.CharField(
                        choices=[
                            ("PRIMARIA", "Primaria"),
                            ("BACHILLER", "Bachiller"),
                            ("TECNICO", "Técnico"),
                            ("TECNOLOGO", "Tecnologo"),
                            ("AUXILIAR", "Auxiliar"),
                            ("UNIVERSITARIO", "Universitario"),
                            ("PROFESIONAL", "Profesional"),
                            ("ESPECIALIZACION", "Especialización"),
                        ],
                        max_length=100,
                        verbose_name="Nivel de Educación",
                    ),
                ),
                (
                    "title",
                    employees.models.models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Título"
                    ),
                ),
                (
                    "ongoing_studies",
                    models.BooleanField(
                        default=False, verbose_name="Estudios en Curso"
                    ),
                ),
            ],
            options={
                "verbose_name": "Educación",
                "verbose_name_plural": "Educación",
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    employees.models.models.CharField(
                        max_length=100, verbose_name="Nombre Contacto de Emergencia"
                    ),
                ),
                (
                    "relationship",
                    employees.models.models.CharField(
                        choices=[
                            ("PADRE", "Padre"),
                            ("MADRE", "Madre"),
                            ("OTRO", "Otro"),
                            ("ABUELO(A)", "Abuelo(a)"),
                            ("AMIGO(A)", "Amigo(a)"),
                            ("HERMANO(A)", "Hermano(a)"),
                            ("ESPOSO(A)", "Esposo(a)"),
                            ("HIJO(A)", "Hijo(a)"),
                            ("TIO(A)", "Tío(a)"),
                            ("PRIMO(A)", "Primo(a)"),
                            ("FAMILIAR", "Familiar"),
                        ],
                        max_length=100,
                        verbose_name="Parentesco",
                    ),
                ),
                (
                    "phone",
                    employees.models.models.CharField(
                        max_length=15, verbose_name="Teléfono de Emergencia"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacto de Emergencia",
                "verbose_name_plural": "Contactos de Emergencia",
            },
        ),
        migrations.CreateModel(
            name="EmploymentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "affiliation_date",
                    models.DateField(verbose_name="Fecha de Afiliación"),
                ),
                ("entry_date", models.DateField(verbose_name="Fecha de Ingreso")),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=65, verbose_name="Salario"
                    ),
                ),
                (
                    "transportation_allowance",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=65,
                        verbose_name="Auxilio de Transporte",
                    ),
                ),
                (
                    "remote_work",
                    models.BooleanField(default=False, verbose_name="Trabajo Remoto"),
                ),
                (
                    "remote_work_application_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de Aplicación de Teletrabajo",
                    ),
                ),
                (
                    "payroll_account",
                    employees.models.models.CharField(
                        max_length=50, verbose_name="Cuenta de Nómina"
                    ),
                ),
                (
                    "legacy_health_provider",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="CAMBIOS EPS (LEGADO)",
                    ),
                ),
                (
                    "appointment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nombramiento"
                    ),
                ),
                (
                    "legacy_appointment_date",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Fecha de Nombramiento (LEGADO)",
                    ),
                ),
                (
                    "business_area",
                    employees.models.models.CharField(
                        choices=[
                            ("OPERATIVOS", "Operativos"),
                            ("ADMINISTRATIVOS", "Administrativos"),
                        ],
                        max_length=100,
                        verbose_name="Área de Negocio",
                    ),
                ),
                (
                    "contract_type",
                    employees.models.models.CharField(
                        choices=[
                            ("TERMINO INDEFINIDO", "Termino Indefinido"),
                            ("OBRA O LABOR", "Obra o Labor"),
                            ("PRESTACION DE SERVICIOS", "Prestación de Servicios"),
                            ("APRENDIZAJE", "Aprendizaje"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de Contrato",
                    ),
                ),
                (
                    "windows_user",
                    employees.models.models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Usuario de Windows",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalles Laborales",
                "verbose_name_plural": "Detalles Laborales",
            },
        ),
        migrations.CreateModel(
            name="PersonalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to=employees.utilities.user_photo_path,
                        verbose_name="Foto",
                    ),
                ),
                (
                    "identification",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[django.core.validators.MinValueValidator(10000)],
                        verbose_name="Identificación",
                    ),
                ),
                (
                    "last_name",
                    employees.models.models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Apellidos"
                    ),
                ),
                (
                    "first_name",
                    employees.models.models.CharField(
                        max_length=100, verbose_name="Nombres"
                    ),
                ),
                (
                    "document_type",
                    employees.models.models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("TI", "Tarjeta de Identidad"),
                            ("PP", "Pasaporte"),
                            ("RC", "Registro Civil"),
                        ],
                        default="CC",
                        max_length=2,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Fecha de Nacimiento")),
                (
                    "expedition_place",
                    employees.models.models.CharField(
                        max_length=100, verbose_name="Lugar de Expedición"
                    ),
                ),
                (
                    "expedition_date",
                    models.DateField(verbose_name="Fecha de Expedición"),
                ),
                (
                    "gender",
                    employees.models.models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        max_length=1,
                        verbose_name="Género",
                    ),
                ),
                (
                    "rh",
                    employees.models.models.CharField(
                        choices=[
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                        verbose_name="RH",
                    ),
                ),
                (
                    "civil_status",
                    employees.models.models.CharField(
                        choices=[
                            ("SOLTERO(A)", "Soltero(a)"),
                            ("UNION LIBRE", "Unión Libre"),
                            ("CASADO(A)", "Casado(a)"),
                            ("DIVORCIADO(A)", "Divorciado(a)"),
                            ("SEPARADO(A)", "Separado(a)"),
                            ("VIUDO(A)", "Viudo(a)"),
                        ],
                        max_length=25,
                        verbose_name="Estado Civil",
                    ),
                ),
                (
                    "sons",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Número de Hijos",
                    ),
                ),
                (
                    "responsible_persons",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Personas a Cargo",
                    ),
                ),
                (
                    "stratum",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                        verbose_name="Estrato",
                    ),
                ),
                (
                    "shirt_size",
                    employees.models.models.CharField(
                        choices=[
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                            ("XXXL", "XXXL"),
                        ],
                        max_length=4,
                        verbose_name="Talla de Camisa",
                    ),
                ),
                (
                    "pant_size",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(6),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="Talla de Pantalón",
                    ),
                ),
                (
                    "shoe_size",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(20)],
                        verbose_name="Talla de Zapato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Información Personal",
                "verbose_name_plural": "Informaciones Personales",
            },
        ),
        migrations.CreateModel(
            name="TerminationDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "termination_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Terminación"
                    ),
                ),
                (
                    "termination_type",
                    employees.models.models.CharField(
                        blank=True,
                        choices=[
                            ("VOLUNTARIA", "Voluntaria"),
                            ("INVOLUNTARIA", "Involuntaria"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Tipo de Terminación",
                    ),
                ),
                (
                    "termination_reason",
                    employees.models.models.CharField(
                        blank=True,
                        choices=[
                            ("BAJA REMUNERACION", "Baja remuneración"),
                            ("CALAMIDAD FAMILIAR", "Calamidad familiar"),
                            ("CAMBIO DE ACTIVIDAD", "Cambio de actividad"),
                            (
                                "CONFLICTOS EN RELACIONES LABORALES",
                                "Conflictos en relaciones laborales",
                            ),
                            ("DESPLAZAMIENTO", "Desplazamiento"),
                            ("ESTRES LABORAL", "Estrés laboral"),
                            (
                                "FALTA DE HERRAMIENTAS PARA  DESEMPEÑAR LA LABOR",
                                "Falta de herramientas para  desempeñar la labor",
                            ),
                            (
                                "FALTA DE INDUCCION AL INGRESAR",
                                "Falta de inducción al ingresar",
                            ),
                            ("FALTA DE RECONOCIMIENTO", "Falta de reconocimiento"),
                            ("HORARIO LABORAL", "Horario laboral"),
                            (
                                "INCOMPATIBILIDAD CON EL JEFE",
                                "Incompatibilidad con el jefe",
                            ),
                            ("MAL AMBIENTE LABORAL", "Mal ambiente laboral"),
                            ("MOTIVOS DE ESTUDIO", "Motivos de estudio"),
                            ("MOTIVOS DE SALUD", "Motivos de salud"),
                            ("MOTIVOS DE VIAJE", "Motivos de viaje"),
                            ("MOTIVOS PERSONALES", "Motivos personales"),
                            (
                                "NO HAY OPORTUNIDADES DE CRECIMIENTO LABORAL",
                                "No hay oportunidades de crecimiento laboral",
                            ),
                            (
                                "NO HAY OPORTUNIDADES DE ESTUDIAR",
                                "No hay oportunidades de estudiar",
                            ),
                            ("OTRA OFERTA LABORAL", "Otra oferta laboral"),
                            ("OTRO", "Otro"),
                            ("PROBLEMAS PERSONALES", "Problemas personales"),
                            (
                                "TERMINACION DE CONTRATO APRENDIZAJE",
                                "Terminación de contrato aprendizaje",
                            ),
                            (
                                "TERMINACION DE CONTRATO CON JUSTA CAUSA",
                                "Terminación de contrato con justa causa",
                            ),
                            (
                                "TERMINACION DE CONTRATO POR PERIODO DE PRUEBA",
                                "Terminación de contrato por periodo de prueba",
                            ),
                            (
                                "TERMINACION DE CONTRATO SIN JUSTA CAUSA",
                                "Terminación de contrato sin justa causa",
                            ),
                            (
                                "TERMINACION POR ABANDONO DE PUESTO",
                                "Terminación por abandono de puesto",
                            ),
                            (
                                "TERMINACION POR OBRA O LABOR CONTRATADA ",
                                "Terminación por obra o labor contratada ",
                            ),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Motivo de Terminación",
                    ),
                ),
                (
                    "rehire_eligibility",
                    models.BooleanField(
                        default=True, verbose_name="Elegible para Recontratación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalles de Terminación",
                "verbose_name_plural": "Detalles de Terminación",
            },
        ),
        migrations.RemoveIndex(
            model_name="employee",
            name="employees_e_identif_e4c381_idx",
        ),
        migrations.RemoveIndex(
            model_name="employee",
            name="employees_e_windows_66265b_idx",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="address",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="affiliation_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="appointment_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="bank",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="business_area",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="cell_phone",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="civil_status",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="compensation_fund",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="contract_type",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="corporate_email",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="education_level",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="emergency_phone",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="emergency_relationship",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="entry_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="expedition_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="expedition_place",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="fixed_phone",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="headquarter",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="health_provider",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="identification",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="legacy_appointment_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="legacy_health_provider",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="locality",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="management",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="memo_1",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="memo_2",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="memo_3",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="neighborhood",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="ongoing_studies",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="pant_size",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="payroll_account",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="pension_fund",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="rehire_eligibility",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="remote_work",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="remote_work_application_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="responsible_persons",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="rh",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="salary",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="saving_fund",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="shirt_size",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="shoe_size",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="sons",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="stratum",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="termination_date",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="termination_reason",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="termination_type",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="title",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="transportation_allowance",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="windows_user",
        ),
        migrations.AddField(
            model_name="contactinformation",
            name="locality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="administration.locality",
                verbose_name="Localidad",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="contact_info",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to="employees.contactinformation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="education",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to="employees.education",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="emergency_contact",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to="employees.emergencycontact",
            ),
        ),
        migrations.AddField(
            model_name="employmentdetails",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="administration.bank",
                verbose_name="Banco",
            ),
        ),
        migrations.AddField(
            model_name="employmentdetails",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="administration.campaign",
                verbose_name="Campaña",
            ),
        ),
        migrations.AddField(
            model_name="employmentdetails",
            name="compensation_fund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="administration.compensationfund",
                verbose_name="Caja de Compensación",
            ),
        ),
        migrations.AddField(
            model_name="employmentdetails",
            name="headquarter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="administration.headquarter",
                verbose_name="Sede",
            ),
        ),
        migrations.AddField(
            model_name="employmentdetails",
            name="health_provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="administration.healthprovider",
                verbose_name="EPS",
            ),
        ),
        migrations.AddField(
            model_name="employmentdetails",
            name="job_title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="administration.jobtitle",
                verbose_name="Cargo",
            ),
        ),
        migrations.AddField(
            model_name="employmentdetails",
            name="management",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="administration.management",
                verbose_name="Gerencia",
            ),
        ),
        migrations.AddField(
            model_name="employmentdetails",
            name="pension_fund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="administration.pensionfund",
                verbose_name="Fondo de Pensiones",
            ),
        ),
        migrations.AddField(
            model_name="employmentdetails",
            name="saving_fund",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="administration.savingfund",
                verbose_name="Cesantías",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_details",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to="employees.employmentdetails",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="personal_info",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to="employees.personalinformation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="termination_details",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to="employees.terminationdetails",
            ),
            preserve_default=False,
        ),
    ]
