# Generated by Django 5.1.3 on 2024-12-03 15:46

import django.db.models.deletion
from django.db import migrations, models

import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0009_jobtitle_rank"),
        (
            "employees",
            "0039_alter_employee_contact_info_alter_employee_education_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="termination_details",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to="employees.terminationdetails",
            ),
        ),
        migrations.AlterField(
            model_name="employmentdetails",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="administration.bank",
                verbose_name="Banco",
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="civil_status",
            field=employees.models.models.CharField(
                choices=[
                    ("SOLTERO(A)", "Soltero(a)"),
                    ("UNION LIBRE", "Unión Libre"),
                    ("CASADO(A)", "Casado(a)"),
                    ("DIVORCIADO(A)", "Divorciado(a)"),
                    ("SEPARADO(A)", "Separado(a)"),
                    ("VIUDO(A)", "Viudo(a)"),
                ],
                default="SOLTERO(A)",
                max_length=25,
                verbose_name="Estado Civil",
            ),
        ),
        migrations.AlterField(
            model_name="personalinformation",
            name="rh",
            field=employees.models.models.CharField(
                choices=[
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                default="O+",
                max_length=3,
                verbose_name="RH",
            ),
        ),
    ]
