# Generated by Django 5.1.3 on 2024-12-05 20:31

import employees.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0040_alter_employee_termination_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=employees.utilities.user_photo_path, verbose_name='Foto'),
        ),
    ]
