# Generated by Django 5.1.3 on 2024-12-11 21:47

import django.core.validators
from django.db import migrations, models

import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0041_alter_personalinformation_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinformation",
            name="cell_phone",
            field=models.CharField(
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+(\\d{11,14})$|^3\\d{9}$", "Número celular inválido."
                    )
                ],
                verbose_name="Celular",
            ),
        ),
        migrations.AlterField(
            model_name="contactinformation",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Correo Electrónico",
            ),
        ),
    ]
