# Generated by Django 5.1 on 2024-09-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_campaign_status_compensationfund_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compensationfund',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pensionfund',
            name='status',
        ),
    ]
