# Generated by Django 5.1 on 2024-09-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_campaign_status_alter_healthprovider_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='rank',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
