# Generated by Django 5.1.3 on 2024-12-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0007_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
    ]
