# Generated by Django 4.2.11 on 2024-09-05 19:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_rename_headquarters_headquarter_and_more'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='headquarter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.headquarter', verbose_name='Sede'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='civil_status',
            field=models.CharField(choices=[('S', 'Soltero(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('U', 'Unión Libre'), ('P', 'Separado(a)'), ('V', 'Viudo(a)')], max_length=1, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='compensation_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.compensationfund', verbose_name='Caja de Compensación'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='corporate_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico Corporativo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.department', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='document_type',
            field=models.CharField(default='CC', max_length=2, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='expedition_date',
            field=models.DateField(verbose_name='Fecha de Expedición'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='expedition_place',
            field=models.CharField(max_length=100, verbose_name='Lugar de Expedición'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='health_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.healthprovider', verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.jobtitle', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.locality', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pension_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.pensionfund', verbose_name='Fondo de Pensiones'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rh',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, verbose_name='RH'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='saving_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.savingfund', verbose_name='Cesantías'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sons',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Número de Hijos'),
        ),
    ]
