# Generated by Django 4.2.11 on 2024-09-05 20:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_bank'),
        ('employees', '0002_employee_headquarter_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='affiliation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Afiliación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Nombramiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.bank', verbose_name='Banco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='business_area',
            field=models.CharField(choices=[('Operativos', 'Operativos'), ('Administrativos', 'Administrativos')], default='Operativo', max_length=100, verbose_name='Área de Negocio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.campaign', verbose_name='Campaña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('Termino Indefinido', 'Termino Indefinido'), ('Termino Fijo', 'Termino Fijo'), ('Obra o Labor', 'Obra o Labor'), ('Prestación de Servicios', 'Prestación de Servicios'), ('Aprendizaje', 'Aprendizaje')], default='Obra labor', max_length=100, verbose_name='Tipo de Contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='education_level',
            field=models.CharField(choices=[('Primaria', 'Primaria'), ('Bachiller', 'Bachiller'), ('Técnico', 'Técnico'), ('Tecnológico', 'Tecnológico'), ('Auxiliar', 'Auxiliar'), ('Universitario', 'Universitario'), ('Profesional', 'Profesional'), ('Especialización', 'Especialización')], default='Bachiller', max_length=100, verbose_name='Nivel de Educación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(default=12321, max_length=100, verbose_name='Contacto de Emergencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_phone',
            field=models.CharField(default=31231, max_length=15, verbose_name='Teléfono de Emergencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_relationship',
            field=models.CharField(default=3213213, max_length=100, verbose_name='Parentesco Contacto de Emergencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='fixed_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Fijo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='management',
            field=models.ForeignKey(default=41, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='administration.management', verbose_name='Gerencia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='neighborhood',
            field=models.CharField(default=453534, max_length=100, verbose_name='Barrio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='ongoing_studies',
            field=models.BooleanField(default=False, verbose_name='Estudios en Curso'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pant_size',
            field=models.PositiveIntegerField(default=534, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(50)], verbose_name='Talla de Pantalón'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='payroll_account',
            field=models.CharField(default=345345435, max_length=50, verbose_name='Cuenta de Nómina'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='remote_work',
            field=models.BooleanField(default=False, verbose_name='Trabajo Remoto'),
        ),
        migrations.AddField(
            model_name='employee',
            name='remote_work_application_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Aplicación de Trabajo Remoto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='responsible_persons',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Personas a Cargo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=42343, max_digits=65, verbose_name='Salario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='shirt_size',
            field=models.PositiveIntegerField(default=31231, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(50)], verbose_name='Talla de Camisa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='shoe_size',
            field=models.PositiveIntegerField(default=312, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(50)], verbose_name='Talla de Zapato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='stratum',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Estrato'),
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(default=3213, max_length=150, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='transportation_allowance',
            field=models.DecimalField(decimal_places=2, default=32131, max_digits=65, verbose_name='Auxilio de Transporte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='identification',
            field=models.CharField(max_length=10, unique=True, verbose_name='Identificación'),
        ),
    ]
