# Generated by Django 5.0.7 on 2024-09-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_civil_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact',
            field=models.CharField(max_length=100, verbose_name='Nombre Contacto de Emergencia'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_relationship',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Otro', 'Otro'), ('Abuelo(a)', 'Abuelo(a)'), ('Amigo(a)', 'Amigo(a)'), ('Hermano(a)', 'Hermano(a)'), ('Esposo(a)', 'Esposo(a)'), ('Hijo(a)', 'Hijo(a)'), ('Tío(a)', 'Tío(a)'), ('Primo(a)', 'Primo(a)'), ('Familiar', 'Familiar')], max_length=100, verbose_name='Parentesco Contacto de Emergencia'),
        ),
    ]
