# Generated by Django 5.0.7 on 2024-09-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employee_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='identification',
            field=models.IntegerField(unique=True, verbose_name='Identificación'),
        ),
    ]
