# Generated by Django 5.0.7 on 2024-09-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_employee_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_email_8f5bbc_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_corpora_fff004_idx',
        ),
    ]
