# Generated by Django 5.0.7 on 2024-09-11 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_remove_employee_employees_e_email_8f5bbc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pant_size',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(50)], verbose_name='Talla de Pantalón'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shirt_size',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(50)], verbose_name='Talla de Camisa'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shoe_size',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(50)], verbose_name='Talla de Zapato'),
        ),
    ]
