# Generated by Django 5.1 on 2024-09-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_employee_legacy_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='memo_1',
            field=models.TextField(blank=True, null=True, verbose_name='Memorando_1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='memo_2',
            field=models.TextField(blank=True, null=True, verbose_name='Memorando_2'),
        ),
        migrations.AddField(
            model_name='employee',
            name='memo_3',
            field=models.TextField(blank=True, null=True, verbose_name='Memorando_3'),
        ),
    ]
