# Generated by Django 5.1 on 2024-09-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_alter_employee_contract_type_alter_employee_stratum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='updated_at',
        ),
    ]
