# Generated by Django 5.1 on 2024-09-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_delete_department'),
        ('employees', '0028_alter_employee_shirt_size_alter_employee_shoe_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='administration.bank', verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='administration.campaign', verbose_name='Campaña'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='compensation_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='administration.compensationfund', verbose_name='Caja de Compensación'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='headquarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='administration.headquarter', verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='health_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='administration.healthprovider', verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='administration.jobtitle', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='locality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='administration.locality', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='administration.management', verbose_name='Gerencia'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pension_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='administration.pensionfund', verbose_name='Fondo de Pensiones'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='saving_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='administration.savingfund', verbose_name='Cesantías'),
        ),
    ]
