# Generated by Django 5.1.3 on 2024-11-26 13:58

import employees.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0037_alter_contactinformation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='photo',
            field=models.ImageField(null=True, upload_to=employees.utilities.user_photo_path, verbose_name='Foto'),
        ),
    ]
