# Generated by Django 5.1.3 on 2024-11-28 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_jobtitle_rank'),
        ('employees', '0001_squashed_0038_alter_personalinformation_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employees.contactinformation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employees.education'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employees.employmentdetails'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employees.personalinformation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='termination_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employees.terminationdetails'),
        ),
        migrations.AlterField(
            model_name='employmentdetails',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='administration.bank', verbose_name='Banco'),
        ),
    ]
