# Generated by Django 5.1 on 2024-09-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
    ]
